apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: ${jsonencode(NAME)}
  namespace: ${jsonencode(NAMESPACE)}
spec:
  targetGroupARN: ${jsonencode(TARGET_GROUP_ARN)}
  targetType: ip
  serviceRef:
    name: ${jsonencode(SERVICE_NAME)}
    port: ${jsonencode(SERVICE_PORT)}
