apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "of-load.fullname" . }}
  labels:
    {{- include "of-load.labels" . | nindent 4 }}
data:
  levels.json: |
    {{- dict "levels" .Values.levels | toJson | nindent 4 }}
