{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "of-load.fullname" . }}
  labels:
    {{- include "of-load.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    {{- if .Values.secrets.usePodIdentity }}
    usePodIdentity: "true"
    {{- end }}
    objects: |
      - objectName: {{ .Values.secrets.name | default .Release.Name | quote }}
        objectType: secretsmanager
        jmesPath:
          {{- range .Values.secrets.keys }}
          - path: {{ . | quote }}
            objectAlias: {{ . | quote }}
          {{- end }}
{{- end }}
