apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${NAME}
  namespace: ${ARGOCD_NAMESPACE}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ${PROJECT}
  source:
    repoURL: "${REPO_URL}"
    targetRevision: "${TARGET_REVISION}"
    path: "${CHART_PATH}"
    helm:
      valueFiles:
        - values.yaml
        - values-${ARCHITECTURE}.yaml
      valuesObject:
        containerPort: ${CONTAINER_PORT}
        targetGroupBinding:
          targetGroupARN: "${TARGET_GROUP_ARN}"
  destination:
    server: https://kubernetes.default.svc
    namespace: ${NAMESPACE}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
