{{- if .Values.secrets.enabled }}
{{- $appSecret := .Values.secrets.app.name | default .Release.Name }}
{{- $dbSecret := required "secrets.db.name is required" .Values.secrets.db.name }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "of-api.fullname" . }}
  labels:
    {{- include "of-api.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider: aws
  parameters:
    {{- if .Values.secrets.usePodIdentity }}
    usePodIdentity: "true"
    {{- end }}
    objects: |
      - objectName: {{ $appSecret | quote }}
        objectType: secretsmanager
        jmesPath:
          {{- range .Values.secrets.app.keys }}
          - path: {{ . | quote }}
            objectAlias: {{ . | quote }}
          {{- end }}
      - objectName: {{ $dbSecret | quote }}
        objectType: secretsmanager
        jmesPath:
          {{- range $path, $alias := .Values.secrets.db.keys }}
          - path: {{ $path | quote }}
            objectAlias: {{ $alias | quote }}
          {{- end }}
{{- end }}
